import { CattleRecord } from '../types';

export const SAMPLE_CATTLE: CattleRecord[] = [
  {
    id: 'kc-104',
    tagNumber: 'KC104',
    name: 'Valli (வள்ளி)',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-27',
    ageYears: { value: 5, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Mayilai)',
    purpose: 'dairy',
    calvingCount: { value: 2, state: 'known' },
    lactationMonth: { value: 4, state: 'known' },
    dailyMilkLiters: { value: 2.8, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 5.0, state: 'estimated', unit: 'L/day' },
    fatPercentage: { value: 4.8, state: 'estimated', unit: '%' },
    productivityTrend: 'decreasing',
    lastLactationDays: { value: 120, state: 'estimated' },
    healthStatus: 'moderate',
    vaccinationStatus: 'partially_vaccinated',
    recentHealthProblems: 'Mild digestive upset & sluggish appetite in last 2 weeks',
    medicalExpensesMonth: { value: 650, state: 'estimated', unit: '₹' },
    bodyScore: { value: 3.2, state: 'known' },
    dailyFeedKg: { value: 16, state: 'estimated', unit: 'kg/day' },
    dailyFeedCostRs: { value: 125, state: 'estimated', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 52, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 800, state: 'unknown', unit: '₹/month' },
    estimatedMarketValueRs: { value: 68000, state: 'estimated', unit: '₹' },
    breedingHistoryNote: 'Conceived via natural service in 2nd parity. 3rd estrus expected in 2 months.',
    milkHistory: [
      { month: 'May', liters: 4.9 },
      { month: 'Jun', liters: 4.6 },
      { month: 'Jul', liters: 3.8 },
      { month: 'Aug', liters: 2.8 },
    ],
    costHistory: [
      { month: 'May', feedCost: 3600, vetCost: 200 },
      { month: 'Jun', feedCost: 3700, vetCost: 300 },
      { month: 'Jul', feedCost: 3800, vetCost: 800 },
      { month: 'Aug', feedCost: 3750, vetCost: 650 },
    ],
  },
  {
    id: 'kc-108',
    tagNumber: 'KC108',
    name: 'Karpagam (கற்பகம்)',
    createdAt: '2026-08-15',
    updatedAt: '2026-08-27',
    ageYears: { value: 3.2, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Kaari)',
    purpose: 'breeding',
    calvingCount: { value: 1, state: 'known' },
    lactationMonth: { value: 2, state: 'known' },
    dailyMilkLiters: { value: 3.8, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 4.2, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 5.2, state: 'known', unit: '%' },
    productivityTrend: 'increasing',
    healthStatus: 'excellent',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'None. Energetic & clear eyes.',
    medicalExpensesMonth: { value: 150, state: 'known', unit: '₹' },
    bodyScore: { value: 4.6, state: 'known' },
    dailyFeedKg: { value: 18, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 110, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 55, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 600, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 145000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Direct lineage of champion Kangeyam stud bull. Superior hump and compact stance.',
    milkHistory: [
      { month: 'Jun', liters: 3.2 },
      { month: 'Jul', liters: 3.6 },
      { month: 'Aug', liters: 3.8 },
    ],
    costHistory: [
      { month: 'Jun', feedCost: 3200, vetCost: 150 },
      { month: 'Jul', feedCost: 3300, vetCost: 100 },
      { month: 'Aug', feedCost: 3300, vetCost: 150 },
    ],
  },
  {
    id: 'kc-102',
    tagNumber: 'KC102',
    name: 'Ganga (கங்கா)',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-27',
    ageYears: { value: 4.5, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Mayilai)',
    purpose: 'dairy',
    calvingCount: { value: 2, state: 'known' },
    lactationMonth: { value: 3, state: 'known' },
    dailyMilkLiters: { value: 4.9, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 5.4, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 5.0, state: 'known', unit: '%' },
    productivityTrend: 'stable',
    healthStatus: 'good',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'None reported.',
    medicalExpensesMonth: { value: 200, state: 'known', unit: '₹' },
    bodyScore: { value: 4.0, state: 'known' },
    dailyFeedKg: { value: 17, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 115, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 54, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 700, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 85000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Timely heat cycles recorded every 21 days.',
    milkHistory: [
      { month: 'May', liters: 4.8 },
      { month: 'Jun', liters: 5.1 },
      { month: 'Jul', liters: 4.9 },
      { month: 'Aug', liters: 4.9 },
    ],
    costHistory: [
      { month: 'May', feedCost: 3400, vetCost: 200 },
      { month: 'Jun', feedCost: 3450, vetCost: 150 },
      { month: 'Jul', feedCost: 3450, vetCost: 200 },
      { month: 'Aug', feedCost: 3450, vetCost: 200 },
    ],
  },
  {
    id: 'kc-95',
    tagNumber: 'KC95',
    name: 'Petchi (பேச்சி)',
    createdAt: '2026-07-20',
    updatedAt: '2026-08-27',
    ageYears: { value: 9.5, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam Standard',
    purpose: 'dairy',
    calvingCount: { value: 6, state: 'known' },
    lactationMonth: { value: 8, state: 'known' },
    dailyMilkLiters: { value: 1.1, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 3.5, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 4.2, state: 'known', unit: '%' },
    productivityTrend: 'decreasing',
    healthStatus: 'poor',
    vaccinationStatus: 'unvaccinated',
    recentHealthProblems: 'Recurrent mastitis in left quarter, severe tooth wear',
    medicalExpensesMonth: { value: 1600, state: 'known', unit: '₹' },
    bodyScore: { value: 2.1, state: 'known' },
    dailyFeedKg: { value: 14, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 135, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 48, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 1200, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 28000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Multiple failed inseminations over past 9 months.',
    milkHistory: [
      { month: 'May', liters: 2.4 },
      { month: 'Jun', liters: 1.8 },
      { month: 'Jul', liters: 1.4 },
      { month: 'Aug', liters: 1.1 },
    ],
    costHistory: [
      { month: 'May', feedCost: 3900, vetCost: 1100 },
      { month: 'Jun', feedCost: 4000, vetCost: 1400 },
      { month: 'Jul', feedCost: 4050, vetCost: 1550 },
      { month: 'Aug', feedCost: 4050, vetCost: 1600 },
    ],
  },
  // Case 1: High milk + high maintenance cost
  {
    id: 'kc-case-1',
    tagNumber: 'CASE1-HIGH-COST',
    name: 'Malar (மலர்)',
    createdAt: '2026-08-20',
    updatedAt: '2026-08-27',
    ageYears: { value: 5.5, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Mayilai)',
    purpose: 'dairy',
    calvingCount: { value: 3, state: 'known' },
    lactationMonth: { value: 3, state: 'known' },
    dailyMilkLiters: { value: 4.8, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 5.2, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 4.6, state: 'known', unit: '%' },
    productivityTrend: 'stable',
    healthStatus: 'moderate',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'High feed intake required, chronic hoof soreness',
    medicalExpensesMonth: { value: 1400, state: 'known', unit: '₹' },
    bodyScore: { value: 3.4, state: 'known' },
    dailyFeedKg: { value: 24, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 210, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 52, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 1500, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 72000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Parity 3 completed cleanly.',
  },
  // Case 2: Vaccination overdue
  {
    id: 'kc-case-2',
    tagNumber: 'CASE2-VAX-OVERDUE',
    name: 'Sundari (சுந்தரி)',
    createdAt: '2026-08-20',
    updatedAt: '2026-08-27',
    ageYears: { value: 4.0, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Sevalai)',
    purpose: 'dairy',
    calvingCount: { value: 2, state: 'known' },
    lactationMonth: { value: 2, state: 'known' },
    dailyMilkLiters: { value: 4.2, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 4.5, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 4.9, state: 'known', unit: '%' },
    productivityTrend: 'stable',
    healthStatus: 'good',
    vaccinationStatus: 'unvaccinated',
    recentHealthProblems: 'Missed FMD round due to monsoon flooding',
    medicalExpensesMonth: { value: 100, state: 'known', unit: '₹' },
    bodyScore: { value: 3.8, state: 'known' },
    dailyFeedKg: { value: 16, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 110, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 53, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 600, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 78000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Timely cycles.',
  },
  // Case 5: Young animal + limited history
  {
    id: 'kc-case-5',
    tagNumber: 'CASE5-YOUNG-HEIFER',
    name: 'Chinnaponnu (சின்னபொண்ணு)',
    createdAt: '2026-08-22',
    updatedAt: '2026-08-27',
    ageYears: { value: 2.4, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Mayilai)',
    purpose: 'dairy',
    calvingCount: { value: 1, state: 'known' },
    lactationMonth: { value: 1, state: 'known' },
    dailyMilkLiters: { value: 2.9, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 3.2, state: 'estimated', unit: 'L/day' },
    fatPercentage: { value: 4.7, state: 'estimated', unit: '%' },
    productivityTrend: 'stable',
    healthStatus: 'good',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'First lactation heifer, adapting to milking stall',
    medicalExpensesMonth: { value: 200, state: 'estimated', unit: '₹' },
    bodyScore: { value: 3.6, state: 'known' },
    dailyFeedKg: { value: 15, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 95, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 54, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 500, state: 'estimated', unit: '₹/month' },
    estimatedMarketValueRs: { value: 85000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'First calving at 27 months.',
  },
  // Case 6: Sudden productivity decrease
  {
    id: 'kc-case-6',
    tagNumber: 'CASE6-SUDDEN-DROP',
    name: 'Bhavani (பவானி)',
    createdAt: '2026-08-24',
    updatedAt: '2026-08-27',
    ageYears: { value: 4.8, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam (Mayilai)',
    purpose: 'dairy',
    calvingCount: { value: 2, state: 'known' },
    lactationMonth: { value: 3, state: 'known' },
    dailyMilkLiters: { value: 2.2, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 5.2, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 4.3, state: 'known', unit: '%' },
    productivityTrend: 'decreasing',
    healthStatus: 'moderate',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'Sudden drop in milk yield over past 4 days, slight warmth in right quarter',
    medicalExpensesMonth: { value: 450, state: 'known', unit: '₹' },
    bodyScore: { value: 3.3, state: 'known' },
    dailyFeedKg: { value: 16, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 120, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 52, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 700, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 75000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Calved 3 months ago.',
  },
  // Case 11: Conflicting data
  {
    id: 'kc-case-11',
    tagNumber: 'CASE11-CONFLICT-DATA',
    name: 'Annam (அன்னம்)',
    createdAt: '2026-08-25',
    updatedAt: '2026-08-27',
    ageYears: { value: 4.0, state: 'known', unit: 'years' },
    gender: 'female',
    breed: 'Kangeyam Standard',
    purpose: 'dairy',
    calvingCount: { value: 2, state: 'known' },
    lactationMonth: { value: 3, state: 'known' },
    dailyMilkLiters: { value: 2.4, state: 'known', unit: 'L/day' },
    historicalPeakMilkLiters: { value: 5.5, state: 'known', unit: 'L/day' },
    fatPercentage: { value: 4.5, state: 'known', unit: '%' },
    productivityTrend: 'increasing', // Conflict: says increasing, but current is 2.4L vs peak 5.5L
    healthStatus: 'good',
    vaccinationStatus: 'fully_vaccinated',
    recentHealthProblems: 'None',
    medicalExpensesMonth: { value: 300, state: 'known', unit: '₹' },
    bodyScore: { value: 3.5, state: 'known' },
    dailyFeedKg: { value: 15, state: 'known', unit: 'kg/day' },
    dailyFeedCostRs: { value: 110, state: 'known', unit: '₹/day' },
    dailyMilkPricePerLiter: { value: 50, state: 'known', unit: '₹/L' },
    monthlyMaintenanceCostRs: { value: 600, state: 'known', unit: '₹/month' },
    estimatedMarketValueRs: { value: 65000, state: 'known', unit: '₹' },
    breedingHistoryNote: 'Normal estrus.',
  },
];

